# Generated by Django 3.0.6 on 2020-06-06 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='group name')),
                ('content', models.TextField(verbose_name='description')),
                ('registration_datetime', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='registration datetime')),
                ('is_approved', models.BooleanField(default=0, verbose_name='is approved')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('related_subjects', models.ManyToManyField(blank=True, to='subjects.Subject')),
            ],
        ),
    ]
