# Generated by Django 3.0.6 on 2020-06-05 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studygroups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='content',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='is_approved',
            field=models.BooleanField(default=0, verbose_name='is approved'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='name',
            field=models.CharField(max_length=40, verbose_name='group name'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='registration_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='registration datetime'),
        ),
    ]
