# Generated by Django 3.0.6 on 2020-06-06 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='current year')),
                ('grade', models.IntegerField(choices=[(10, '10º'), (11, '11º'), (12, '12º')], default=10, verbose_name='grade')),
                ('abc', models.CharField(default='A', max_length=2, verbose_name='class')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Course', verbose_name='course')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='director')),
                ('students', models.ManyToManyField(related_name='classes', to=settings.AUTH_USER_MODEL, verbose_name='students')),
            ],
            options={
                'unique_together': {('year', 'grade', 'abc')},
            },
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subjects', to='classes.Class', verbose_name='class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='classes', to='subjects.Subject', verbose_name='subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='teacher')),
            ],
            options={
                'unique_together': {('subject', 'klass', 'teacher')},
            },
        ),
    ]
