# Generated by Django 3.0.6 on 2020-06-05 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_auto_20200605_2109'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_auto_20200605_2109'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='abc',
            field=models.CharField(default='A', max_length=2, verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='class',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Course', verbose_name='course'),
        ),
        migrations.AlterField(
            model_name='class',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='director'),
        ),
        migrations.AlterField(
            model_name='class',
            name='grade',
            field=models.IntegerField(choices=[(10, '10º'), (11, '11º'), (12, '12º')], default=10, verbose_name='grade'),
        ),
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(related_name='classes', to=settings.AUTH_USER_MODEL, verbose_name='students'),
        ),
        migrations.AlterField(
            model_name='class',
            name='year',
            field=models.IntegerField(verbose_name='current year'),
        ),
        migrations.AlterField(
            model_name='classsubject',
            name='klass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subjects', to='classes.Class', verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='classsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='classes', to='subjects.Subject', verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='classsubject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='teacher'),
        ),
    ]
