# Generated by Django 3.0.6 on 2020-06-06 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('file', models.FileField(upload_to='class/', verbose_name='Ficheiro')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Hora')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='classes.ClassSubject', verbose_name='Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('happens_at', models.DateField(null=True)),
                ('starts_at', models.TimeField()),
                ('ends_at', models.TimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='classes.ClassSubject')),
            ],
            options={
                'ordering': ['-happens_at', '-starts_at', '-ends_at'],
            },
        ),
    ]
