# Generated by Django 3.0.6 on 2020-06-04 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('klass', '0002_auto_20200604_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='klass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='classes.Class'),
        ),
    ]
