# Generated by Django 3.0.6 on 2020-06-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klass', '0003_auto_20200604_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='happening_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='ends_at',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='starts_at',
            field=models.TimeField(),
        ),
    ]
