# Generated by Django 3.0.6 on 2020-06-04 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('klass', '0005_auto_20200604_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-happens_at', '-starts_at', '-ends_at']},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='klass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='classes.ClassSubject'),
        ),
    ]
