# Generated by Django 3.0.6 on 2020-06-04 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klass', '0006_auto_20200604_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='klass',
            new_name='subject',
        ),
    ]
