# Generated by Django 3.0.6 on 2020-06-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.IntegerField(choices=[(1, 'Very bad'), (2, 'Bad'), (3, 'Satisfactory'), (4, 'Good'), (5, 'Excellent')]),
        ),
        migrations.AlterField(
            model_name='poll',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.CharField(max_length=200, verbose_name='content'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
