# Generated by Django 3.0.6 on 2020-06-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200605_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.IntegerField(blank=None, choices=[(1, 'Very bad'), (2, 'Bad'), (3, 'Satisfactory'), (4, 'Good'), (5, 'Excellent')]),
        ),
    ]
